### ISSUE TITLE
Crashing after a few recursive lookups

### ISSUE THREAD

**Issue by Azothyran** [fashni/lrc-generator#14]
The command I'm running is:
`mxlrc.exe --token 2307233d031af73b331a2206ba7e49b793c15c613a48d523e42653 -d 5 -t 60 -s "H:\AUDIO\FLAC\CD-res\ROCK\NEED_LYRICS"`

And after a couple of songs finish, I get this error. If I re-run the command sometimes it will work, other times it might repeatedly spit the error out several times but then decide to start working again. It seems very random so I am unable to find a specific cause. It is sometimes able to traverse a few directories and work on several of my artist folders, other times it can barely make it past a few songs of a single album.

```[+] Searching song: Linkin Park - Lies Greed Misery
[+] Song found: Linkin Park - LIES GREED MISERY
[+] Searching lyrics: Linkin Park - LIES GREED MISERY
[+] Formatting lyrics
Lyrics saved: H:\AUDIO\FLAC\CD-res\ROCK\NEED_LYRICS\Linkin Park\2012. Living Things\D1T04 Lies Greed Misery.lrc
    Please wait... 0s

[+] Searching song: Linkin Park - I'll Be Gone
Traceback (most recent call last):
  File "C:\Users\AZOTHY~1\AppData\Local\Temp\ON441D~1\mxlrc.py", line 360, in <module>
  File "C:\Users\AZOTHY~1\AppData\Local\Temp\ON441D~1\mxlrc.py", line 299, in main
  File "C:\Users\AZOTHY~1\AppData\Local\Temp\ON441D~1\mxlrc.py", line 277, in get_lrc
  File "C:\Users\AZOTHY~1\AppData\Local\Temp\ON441D~1\mxlrc.py", line 52, in find_lyrics
KeyError: 'matcher.track.get'

**Comment by Azothyran** [comment]
After this started happening repeatedly with a couple of directories, I generated a new API token to use and the error went away for a while. Maybe song lookups are rate limited as well besides just fetching lyrics and this is causing an ungraceful exit of the program?
